import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import * as XLSX from "xlsx";
import { formatDate } from "./formatters.js";

// jsPDF's default fonts don't reliably render the "₹" glyph, so exports
// use a plain "Rs." prefix instead of formatCurrency()'s Intl symbol.
function plainAmount(amount) {
  const value = Number.isFinite(amount) ? amount : 0;
  return `Rs. ${value.toLocaleString("en-IN")}`;
}

function transactionRows(transactions) {
  return transactions.map((t) => [
    t.type === "income" ? "Income" : "Expense",
    t.category || "",
    t.description || "",
    formatDate(t.date),
    `${t.type === "income" ? "+" : "-"}${plainAmount(t.amount)}`,
  ]);
}

/**
 * Export a list of transactions to a downloadable PDF, with an optional
 * title/subtitle and summary line (e.g. income/expense/net totals).
 */
export function exportTransactionsToPDF(transactions, { title = "BudgetNest Export", subtitle = "", summary = null, filename = "budgetnest-export.pdf" } = {}) {
  const doc = new jsPDF();

  doc.setFontSize(16);
  doc.text(title, 14, 18);

  let cursorY = 26;
  if (subtitle) {
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text(subtitle, 14, cursorY);
    cursorY += 6;
  }

  if (summary) {
    doc.setFontSize(10);
    doc.setTextColor(60);
    const summaryLine = summary
      .map((s) => `${s.label}: ${plainAmount(s.value)}`)
      .join("    |    ");
    doc.text(summaryLine, 14, cursorY);
    cursorY += 6;
  }

  autoTable(doc, {
    startY: cursorY + 2,
    head: [["Type", "Category", "Description", "Date", "Amount"]],
    body: transactionRows(transactions),
    styles: { fontSize: 9, cellPadding: 3 },
    headStyles: { fillColor: [79, 70, 229] },
    columnStyles: { 4: { halign: "right" } },
  });

  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text(
    `Generated by BudgetNest on ${new Date().toLocaleString("en-IN")}`,
    14,
    doc.internal.pageSize.getHeight() - 10
  );

  doc.save(filename);
}

/**
 * Export a list of transactions to a downloadable Excel (.xlsx) workbook.
 * If a summary is provided, it is written as a second sheet.
 */
export function exportTransactionsToExcel(transactions, { sheetName = "Transactions", summary = null, filename = "budgetnest-export.xlsx" } = {}) {
  const rows = transactions.map((t) => ({
    Type: t.type === "income" ? "Income" : "Expense",
    Category: t.category || "",
    Description: t.description || "",
    Date: formatDate(t.date),
    Amount: t.type === "income" ? t.amount : -Math.abs(t.amount),
  }));

  const workbook = XLSX.utils.book_new();
  const sheet = XLSX.utils.json_to_sheet(rows);
  sheet["!cols"] = [{ wch: 10 }, { wch: 18 }, { wch: 30 }, { wch: 14 }, { wch: 14 }];
  XLSX.utils.book_append_sheet(workbook, sheet, sheetName);

  if (summary) {
    const summarySheet = XLSX.utils.json_to_sheet(
      summary.map((s) => ({ Metric: s.label, Amount: s.value }))
    );
    summarySheet["!cols"] = [{ wch: 20 }, { wch: 14 }];
    XLSX.utils.book_append_sheet(workbook, summarySheet, "Summary");
  }

  XLSX.writeFile(workbook, filename);
}
